import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import STEP_1 from "../assets/img/guide_icons/STEP_1.png";
import STEP_2 from "../assets/img/guide_icons/STEP_2.png";
import STEP_3 from "../assets/img/guide_icons/STEP_3.png";
import STEP_4 from "../assets/img/guide_icons/STEP_4.png";
const Guide_Element = () => {
    return (_jsxs("div", { children: [_jsx("h1", { className: "w-full py-16 text-white px-4 text-center text-5xl", children: "Guideline To Contribute" }), _jsxs("div", { className: 'flex flex-wrap justify-center gap-4 md:gap-4 sm:gap-4', children: [_jsxs("a", { className: 'flex flex-col bg-gray-900 rounded-lg text-green-400 hover:bg-green-400 transition-color hover:text-white transition-color', style: { width: '280px', height: '285px' }, href: 'https://github.com/FOSS-Community/website-fossc', children: [_jsx("img", { src: STEP_1, alt: 'Step 1 Icon', className: 'w-40 mx-auto mt-4 mb-3' }), _jsx("h2", { className: 'text-center font-bold text-xl mb-0.5', children: "STEP 1" }), _jsx("p", { className: 'flex flex-col text-center text-white text-md mb-1 px-16', children: "Go to our Github repository" })] }), _jsxs("div", { className: 'flex flex-col bg-gray-900 rounded-lg text-green-400 hover:bg-green-400 transition-color hover:text-white transition-color', style: { width: '280px', height: '285px' }, children: [_jsx("img", { src: STEP_2, alt: 'Step 2 Icon', className: 'w-25 mx-auto' }), _jsx("h2", { className: 'text-center font-bold text-xl my-1', children: "STEP 2" }), _jsx("p", { className: 'flex flex-col text-center text-white text-md mb-1 px-16', children: "Fork the repository to your account" })] }), _jsxs("div", { className: 'flex flex-col bg-gray-900 rounded-lg text-green-400 hover:bg-green-400 transition-color hover:text-white transition-color', style: { width: '280px', height: '285px' }, children: [_jsx("img", { src: STEP_3, alt: 'Step 3 Icon', className: 'w-30 mx-auto' }), _jsx("h2", { className: 'text-center font-bold text-xl my-1', children: "STEP 3" }), _jsx("p", { className: 'flex flex-col text-center text-white text-md mb-1 px-16', children: "Make changes and commit them" })] }), _jsxs("a", { className: 'flex flex-col bg-gray-900 rounded-lg text-green-400 hover:bg-green-400 transition-color hover:text-white transition-color', style: { width: '280px', height: '285px' }, href: 'https://discord.com/channels/983838934624780288/986650931754053644', children: [_jsx("img", { src: STEP_4, alt: 'Step 4 Icon', className: 'w-40 mx-auto mt-10 mb-8' }), _jsx("h2", { className: 'text-center font-bold text-xl my-1', children: "STEP 4" }), _jsx("p", { className: 'flex flex-col text-center text-white text-md px-4', children: "Discuss the commit with maintainer in Discord" })] })] })] }));
};
export default Guide_Element;
